name: Snapcraft release stable

on:
  push:
    tags:
      - 'release-[0-9]+.[0-9]+.[0-9]+'

jobs:
  snapcraft-publish-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with: 
          snap: ${{ steps.build.outputs.snap }}
          release: stable